# Schema for the configuration files of the Paragraphs Types module.

paragraphs_types.settings:
  type: config_object
  label: 'Load Assets'
  mapping:
    load_gallery_assets:
      type: checkbox
      label: 'Load Image Gallary specific JS and CSS assets'
